"""Add user preference.

Revision ID: 022505714cf8
Revises: bed6bc0b197a
Create Date: 2022-04-02 01:37:17.437163

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = '022505714cf8'
down_revision = 'bed6bc0b197a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('domain', sa.Enum('DASHBOARD', name='userpreferencedomain'), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('domain', 'user_name')
    )
    op.create_index(op.f('ix_user_preference_user_name'), 'user_preference', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preference_user_name'), table_name='user_preference')
    op.drop_table('user_preference')
    # ### end Alembic commands ###
